RCUtils:
  autoStop:
    isEnabled: true
    time: 120
  commandBlocks:
    isEnabled: true
    allowedCommands:
      - testfor
      - tell
      - tp
      - msg
      - setBlock
      - gmc
      - gms
      - gamemode
      - give
      - clear
      - ci
      - time
      - settime
      - effect
      - playsound