RCUtils:
  autoStop:
    isEnabled: true
    time: 120
  teleport:
    spawn: world#0#0#0#0#0
    join: world#0#0#0#0#0
    death: world#0#0#0#0#0
  startup: []
  commandBlocks:
    isEnabled: true
    allowedCommands:
      - testfor
      - tell
      - tp
      - msg
      - setBlock
      - gmc
      - gms
      - gamemode
      - give
      - clear
      - ci
      - time
      - settime
      - effect
      - playsound