name: RedstoneCraftUtils
load: STARTUP
main: org.primesoft.redstoneCraftUtils.RCUtilsMain
version: 0.2
website: 
description: Util commands required by my server
authors: [SBPrime]
depend: []
softdepend: []
permissions:
  RCUtils.*:
    description: Grants access to all RedstoneCraftUtils commands permissions
    default: op
    children:
      RCUtils.CommandBlock.*: true
      RCUtils.Reload: true
  RCUtils.Spawn:
    description: Grants access to spawn command
    default: op
  RCUtils.Reload:
    description: Grants access to reload configuration command
    default: op
  RCUtils.CommandBlock.*:
    description: Grants access to all CommandBlocks commands permissions
    default: op
    children:
      RCUtils.CommandBlock.GetBlock: true
      RCUtils.CommandBlock.GetName: true
      RCUtils.CommandBlock.SetName: true
      RCUtils.CommandBlock.GetCommand: true
      RCUtils.CommandBlock.SetCommand: true
  RCUtils.CommandBlock.GetBlock:
    description: Grants access to commandBlockGet command
    default: op
  RCUtils.CommandBlock.GetName:
    description: Grants access to commandBlockGetName command
    default: op
  RCUtils.CommandBlock.SetName:
    description: Grants access to commandBlockSetName command
    default: op
  RCUtils.CommandBlock.GetCommand:
    description: Grants access to commandBlockGetCommand command
    default: op
  RCUtils.CommandBlock.SetCommand:
    description: Grants access to commandBlockSetCommand command
    default: op
    